# Generated by Django 3.1.1 on 2020-09-08 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diabetes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diabeticprediction',
            name='is_diabetic',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
